from enum import Enum

class FormazioneType(str, Enum):
    AUTISTA_ANPAS = 'AUTISTA ANPAS'
    ELI = 'ELI 10 ECG'
    SEDIA_C = 'SEDIA CINGOLATA'
    SEDIA_M = 'SEDIA MOTORIZZATA'
    TRASPORTO_SICUREZZA_PAZIENTE = 'TRASPORTO E SICUREZZA PAZIENTE'
    TRUCCABIMBI = 'TRUCCABIMBI'
    TRUCCATORE_BASE = 'TRUCCATORE BASE ANPAS'
    TRUCCATORE_AVANZATO = 'TRUCCATORE AVANZATO ANPAS'